# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      params:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'testeth params'
        # Default value if no value is explicitly provided
        default: '-- --express'
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  testeth:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install git-lfs
      run: |
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
    - run: git lfs install
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Run testeth
      run: ./testeth ${{ github.event.inputs.params }}
